### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Closes https://github.com/stylelint/postcss-css-in-js/issues/10

> Is there anything in the PR that needs further explanation?

Fires-up the CI. I will standardise the tooling (ESLint etc) in a follow up pull request once https://github.com/stylelint/postcss-css-in-js/pull/17 and https://github.com/stylelint/postcss-css-in-js/pull/18.

~We should merge this and then rebase the other two pull requests.~

We should merge this and then rebase the nested literals fix.

### CODE REVIEW

**Comment by jeddy3** [comment]
The tests aren't passing on Windows. Is this a blocker to release?

**Comment by ota-meshi** [comment]
Hi.

I think you probably need to do the following:

```bash
git config --global core.autocrlf false
```

**Comment by jeddy3** [comment]
> I think you probably need to do the following:

Good shout.  All green now.

**Comment by hudochenkov** [comment]
Why do we need to test it on all OSes? I believe all code is platform independent and there is no file operations.

**Comment by jeddy3** [comment]
> Why do we need to test it on all OSes?

We probably don't. I was just copy-pasting the standard CI tasks so I didn't have to think about it.

**Pull request merged**
