### PR TITLE
Setup official GitHub Dependabot

### PR DESCRIPTION
**Pull request by abdonrd**
> Which issue, if any, is this issue related to?

None, as it's a documentation fix.

> Is there anything in the PR that needs further explanation?

Setup official GitHub Dependabot.

https://docs.github.com/en/github/administering-a-repository/about-github-dependabot-version-updates

> GitHub Dependabot takes the effort out of maintaining your dependencies. You can use it to ensure that your repository automatically keeps up with the latest releases of the packages and applications it depends on.

### CODE REVIEW

**Review by jeddy3 — COMMENTED** [review]
Good shout. 

There's a stylelint organisation-wide dependabot app that isn't turned on for this repository.

Shall I turn it on there, rather than merging this pull request?

**Comment by abdonrd** [comment]
This app is the official by GitHub?

**Comment by jeddy3** [comment]
Yes, it's this one: https://github.com/marketplace/dependabot-preview

I can't find details in the GitHub docs about managing dependabot version updates at an organisational level (other than managing dependabot security alerts, which we already do). As we managed dependabot alerts centrally, it probably makes sense we centrally manage the dependabot version updates too.

**Comment by abdonrd** [comment]
Ok! But this is the old dependabot.

GitHub bought dependabot and integrated it here:
https://github.com/stylelint/postcss-css-in-js/network/updates

**Comment by jeddy3** [comment]
> Ok! But this is the old dependabot.

I figured that was the case. We might as well use the new version in this repository then.

They'll probably add organisational-wide support at later date.

**Pull request merged**
