### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by abdonrd**
> Which issue, if any, is this issue related to?

None, as it's a documentation fix.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]
LGTM, thanks!

You'll want to merge https://github.com/stylelint/postcss-css-in-js/pull/40 first, and then rebase this pull request before merging it.

**Comment by abdonrd** [comment]
@jeddy3 I didn't update mocha, nyc and chai in this PR to avoid conflicts!

**Comment by jeddy3** [comment]
> @jeddy3 I didn't update mocha, nyc and chai in this PR to avoid conflicts!

Unfortunately, it looks like it conflicted anyway. Can you rebase?

**Comment by abdonrd** [comment]
@jeddy3 right! rebased! ⚡

**Comment by jeddy3** [comment]
Thank you!

**Pull request merged**
